In [1]:
## TODO

In [2]:
import numpy as np
import os

# Cell 2: Generate Training Data
# Generate all binary sequences of length 1 to 10 and their final parity labels

In [3]:
def generate_training_data(L_train):
    sequences = []
    labels = []
    for length in range(1, L_train+1):
        for i in range(2**length):
            # binary representation of i, padded
            bits = [(i >> j) & 1 for j in range(length-1, -1, -1)]
            npbits = np.array(bits)
            sequences.append(npbits)
            parity = np.mod(np.sum(bits), 2)
            labels.append(parity)
    return np.array(sequences, dtype=object), np.array(labels, dtype=np.int64)


In [4]:
L_train = 10
train_X, train_Y = generate_training_data(L_train)

for x,y in zip(train_X, train_Y):
  print(x, y)

[0] 0
[1] 1
[0 0] 0
[0 1] 1
[1 0] 1
[1 1] 0
[0 0 0] 0
[0 0 1] 1
[0 1 0] 1
[0 1 1] 0
[1 0 0] 1
[1 0 1] 0
[1 1 0] 0
[1 1 1] 1
[0 0 0 0] 0
[0 0 0 1] 1
[0 0 1 0] 1
[0 0 1 1] 0
[0 1 0 0] 1
[0 1 0 1] 0
[0 1 1 0] 0
[0 1 1 1] 1
[1 0 0 0] 1
[1 0 0 1] 0
[1 0 1 0] 0
[1 0 1 1] 1
[1 1 0 0] 0
[1 1 0 1] 1
[1 1 1 0] 1
[1 1 1 1] 0
[0 0 0 0 0] 0
[0 0 0 0 1] 1
[0 0 0 1 0] 1
[0 0 0 1 1] 0
[0 0 1 0 0] 1
[0 0 1 0 1] 0
[0 0 1 1 0] 0
[0 0 1 1 1] 1
[0 1 0 0 0] 1
[0 1 0 0 1] 0
[0 1 0 1 0] 0
[0 1 0 1 1] 1
[0 1 1 0 0] 0
[0 1 1 0 1] 1
[0 1 1 1 0] 1
[0 1 1 1 1] 0
[1 0 0 0 0] 1
[1 0 0 0 1] 0
[1 0 0 1 0] 0
[1 0 0 1 1] 1
[1 0 1 0 0] 0
[1 0 1 0 1] 1
[1 0 1 1 0] 1
[1 0 1 1 1] 0
[1 1 0 0 0] 0
[1 1 0 0 1] 1
[1 1 0 1 0] 1
[1 1 0 1 1] 0
[1 1 1 0 0] 1
[1 1 1 0 1] 0
[1 1 1 1 0] 0
[1 1 1 1 1] 1
[0 0 0 0 0 0] 0
[0 0 0 0 0 1] 1
[0 0 0 0 1 0] 1
[0 0 0 0 1 1] 0
[0 0 0 1 0 0] 1
[0 0 0 1 0 1] 0
[0 0 0 1 1 0] 0
[0 0 0 1 1 1] 1
[0 0 1 0 0 0] 1
[0 0 1 0 0 1] 0
[0 0 1 0 1 0] 0
[0 0 1 0 1 1] 1
[0 0 1 1 0 0] 0
[0 0 1 1 0 1] 1
[0 0 1 1 1 0

In [5]:
data_path = os.path.join('../data/training', 'train_data.npz')
np.savez_compressed(data_path, X=train_X, Y=train_Y)
print(f"Saved training data to {data_path}")

Saved training data to ../data/training/train_data.npz


# Cell 3: Generate Validation Data
# For each target length, generate num_val random sequences with parity labels.

In [6]:
def generate_validation_data(L_validation, L_sequence):
    sequences = []
    labels = []
    for _ in range(L_validation):
        bits = []
        for _ in range(L_sequence):
            bit = np.random.choice([0, 1])
            bits.append(bit)
        npbits = np.array(bits)
        sequences.append(npbits)
        parity = np.mod(np.sum(bits), 2)
        print("current seq: ", npbits, "parity: ", parity)
        labels.append(parity)
    return np.array(sequences, dtype=object), np.array(labels, dtype=np.int64)

In [7]:
np.random.seed(0)

val_len = 100
seq_len = [25, 50, 100, 250, 1000, 2500, 10000]
validation_data = {seq_len[i]: generate_validation_data(val_len, seq_len[i]) for i in range(len(seq_len))}

current seq:  [0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 0 0 0 1 0 1 1 0 0] parity:  1
current seq:  [1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 0 1 0 1 1 1 1 1 0 1] parity:  1
current seq:  [0 1 1 1 1 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0] parity:  1
current seq:  [1 1 0 1 0 0 1 0 1 1 1 1 1 1 0 1 1 0 0 1 0 0 1 1 0] parity:  1
current seq:  [1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 0 1 0 1 1 1 1 1] parity:  0
current seq:  [0 1 1 1 1 0 1 1 0 0 1 0 0 0 0 1 1 0 0 1 0 1 1 1 1] parity:  0
current seq:  [0 0 0 1 0 1 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 1 0 1] parity:  0
current seq:  [0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0] parity:  1
current seq:  [1 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 1 1] parity:  0
current seq:  [1 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 1 0 1 1 1 1 0 0 0] parity:  1
current seq:  [1 1 1 0 1 1 1 1 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 0 0] parity:  0
current seq:  [0 1 0 1 0 1 1 0 0 0 1 0 0 1 1 1 1 0 1 0 0 0 0 1 1] parity:  0
current seq:  [1 0 1 0 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 0] parity:  0

In [8]:
for vl, vals in validation_data.items():
  data_path = os.path.join('../data/validation', f'val_data_{vl}.npz')
  np.savez_compressed(data_path, X=vals[0], Y=vals[1])
  print(f"Saved training data to {data_path}")

Saved training data to ../data/validation/val_data_25.npz
Saved training data to ../data/validation/val_data_50.npz
Saved training data to ../data/validation/val_data_100.npz
Saved training data to ../data/validation/val_data_250.npz
Saved training data to ../data/validation/val_data_1000.npz
Saved training data to ../data/validation/val_data_2500.npz
Saved training data to ../data/validation/val_data_10000.npz
